# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SliceFL
email:
description: >- # this means to ignore newlines until "baseurl:"
  The SliceFL project aims to test fault localisation methods and increase their efficiency. Our main research areas are spectrum-based fault localisation, program slicing and their combined applications. If you are interested in this topic, you can find our contact details under "About us". Under the "Publications" tab, we list the articles published so far, for which you can find supplementary material under "Downloads".
twitter_username: tba
github_username: tba
minimal_mistakes_skin: dark
search: true
logo: "/assets/images/fllogopre.png"
repository: "samuraisnail/slice-fl"
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
#theme: minimal-mistakes-jekyll
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sass:
  sass_dir: _sass
  style: compressed

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-scholar

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

author:
  name   : "University of Szeged, Department of Software Engineering"
  avatar : "/assets/images/szte.png"
  bio    : "This is the official webpage of the SliceFL project"
  links:
    - label: "University of Szeged"
      icon: "fa-solid fa-landmark-flag"
      url: "https://u-szeged.hu/english"
    - label: "Software Engineering Department"
      icon: "fas fa-fw fa-link"
      url: "https://www.sed.inf.u-szeged.hu"
    - label: "Szeged, Hungary"
      icon: "fa-solid fa-map"
      url: "https://goo.gl/maps/Q6J7LbKDR8CY14GM6"

footer:

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "docs"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "docs"
  - scope:
      path: ""
      type: tag
    values:
      sidebar:
        nav: "docs"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: single
    
    
head_scripts:
    - "https://kit.fontawesome.com/17f857d6c4.js"